name: FunctionalDesignDocumentToTechnicalDesignDocument
description: Generate TDD JSON from file-based FDD using prompt and knowledge rules

instructions:

  - step: load_fdd
    description: |
      Use the Functional Design Document provided in:
      .inputs/fdd.json
      Treat this file as the complete and authoritative FDD source.

  - step: generate_tdd
    description: |
      Generate a Technical Design Document (TDD) strictly following:

      Authoritative rules:
      - .prompts/FDD2TDDSystemMessage.md
      - .knowledge/technical-standards.md

      Constraints:
      - Output JSON only
      - Follow the exact JSON structure defined in the prompt file
      - Use null or empty arrays for missing data
      - Do NOT invent data
      - All validator classes must end with 'Policy'
      - No markdown, explanations, or comments

output:
  format: json
